version: "3"

services:
  php:
    build: .
    ports:
      - "8080:80"
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - vim_modules:/home/docker/.vim/
      - coc_modules:/home/docker/dotfiles/.config/coc/
      - ~/.ssh/:/home/docker/.ssh/
      - ./html:/var/www/html/
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    logging:
      options:
        max-size: "5mb"
        max-file: "3"

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      TZ: "Asia/Tokyo"

volumes:
  vim_modules:
  coc_modules:
  db_data:
